// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	balance "github.com/cashback-platform/services/cashback-service-api/internal/app/user/usecase/balance"
	mock "github.com/stretchr/testify/mock"
)

// BlockchainClient is an autogenerated mock type for the BlockchainClient type
type BlockchainClient struct {
	mock.Mock
}

type BlockchainClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockchainClient) EXPECT() *BlockchainClient_Expecter {
	return &BlockchainClient_Expecter{mock: &_m.Mock}
}

// Balance provides a mock function with given fields: ctx, walletAddress
func (_m *BlockchainClient) Balance(ctx context.Context, walletAddress string) (balance.TokenBalance, error) {
	ret := _m.Called(ctx, walletAddress)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 balance.TokenBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (balance.TokenBalance, error)); ok {
		return rf(ctx, walletAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) balance.TokenBalance); ok {
		r0 = rf(ctx, walletAddress)
	} else {
		r0 = ret.Get(0).(balance.TokenBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, walletAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockchainClient_Balance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balance'
type BlockchainClient_Balance_Call struct {
	*mock.Call
}

// Balance is a helper method to define mock.On call
//   - ctx context.Context
//   - walletAddress string
func (_e *BlockchainClient_Expecter) Balance(ctx interface{}, walletAddress interface{}) *BlockchainClient_Balance_Call {
	return &BlockchainClient_Balance_Call{Call: _e.mock.On("Balance", ctx, walletAddress)}
}

func (_c *BlockchainClient_Balance_Call) Run(run func(ctx context.Context, walletAddress string)) *BlockchainClient_Balance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BlockchainClient_Balance_Call) Return(_a0 balance.TokenBalance, _a1 error) *BlockchainClient_Balance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockchainClient_Balance_Call) RunAndReturn(run func(context.Context, string) (balance.TokenBalance, error)) *BlockchainClient_Balance_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockchainClient creates a new instance of BlockchainClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockchainClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockchainClient {
	mock := &BlockchainClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
