// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// OutboxWriter is an autogenerated mock type for the OutboxWriter type
type OutboxWriter struct {
	mock.Mock
}

type OutboxWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxWriter) EXPECT() *OutboxWriter_Expecter {
	return &OutboxWriter_Expecter{mock: &_m.Mock}
}

// CreateWithTx provides a mock function with given fields: tx, eventType, aggregateType, aggregateID, payload
func (_m *OutboxWriter) CreateWithTx(tx *gorm.DB, eventType string, aggregateType string, aggregateID int64, payload []byte) error {
	ret := _m.Called(tx, eventType, aggregateType, aggregateID, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string, string, int64, []byte) error); ok {
		r0 = rf(tx, eventType, aggregateType, aggregateID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OutboxWriter_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type OutboxWriter_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - tx *gorm.DB
//   - eventType string
//   - aggregateType string
//   - aggregateID int64
//   - payload []byte
func (_e *OutboxWriter_Expecter) CreateWithTx(tx interface{}, eventType interface{}, aggregateType interface{}, aggregateID interface{}, payload interface{}) *OutboxWriter_CreateWithTx_Call {
	return &OutboxWriter_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", tx, eventType, aggregateType, aggregateID, payload)}
}

func (_c *OutboxWriter_CreateWithTx_Call) Run(run func(tx *gorm.DB, eventType string, aggregateType string, aggregateID int64, payload []byte)) *OutboxWriter_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(string), args[2].(string), args[3].(int64), args[4].([]byte))
	})
	return _c
}

func (_c *OutboxWriter_CreateWithTx_Call) Return(_a0 error) *OutboxWriter_CreateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OutboxWriter_CreateWithTx_Call) RunAndReturn(run func(*gorm.DB, string, string, int64, []byte) error) *OutboxWriter_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewOutboxWriter creates a new instance of OutboxWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxWriter {
	mock := &OutboxWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
