// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/cashback-service-api/internal/app/cashback/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *Repository) FindByUserID(ctx context.Context, userID int64) ([]domain.Cashback, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []domain.Cashback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Cashback, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Cashback); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Cashback)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type Repository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *Repository_FindByUserID_Call {
	return &Repository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *Repository_FindByUserID_Call) Run(run func(ctx context.Context, userID int64)) *Repository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_FindByUserID_Call) Return(_a0 []domain.Cashback, _a1 error) *Repository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]domain.Cashback, error)) *Repository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// TotalByUserID provides a mock function with given fields: ctx, userID
func (_m *Repository) TotalByUserID(ctx context.Context, userID int64) (float64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for TotalByUserID")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (float64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) float64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_TotalByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalByUserID'
type Repository_TotalByUserID_Call struct {
	*mock.Call
}

// TotalByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repository_Expecter) TotalByUserID(ctx interface{}, userID interface{}) *Repository_TotalByUserID_Call {
	return &Repository_TotalByUserID_Call{Call: _e.mock.On("TotalByUserID", ctx, userID)}
}

func (_c *Repository_TotalByUserID_Call) Run(run func(ctx context.Context, userID int64)) *Repository_TotalByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_TotalByUserID_Call) Return(_a0 float64, _a1 error) *Repository_TotalByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_TotalByUserID_Call) RunAndReturn(run func(context.Context, int64) (float64, error)) *Repository_TotalByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
