// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/cashback-service-api/internal/app/purchase/domain"
	mock "github.com/stretchr/testify/mock"
)

// PurchaseRepository is an autogenerated mock type for the PurchaseRepository type
type PurchaseRepository struct {
	mock.Mock
}

type PurchaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PurchaseRepository) EXPECT() *PurchaseRepository_Expecter {
	return &PurchaseRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PurchaseRepository) FindByID(ctx context.Context, id int64) (domain.Purchase, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Purchase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Purchase, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Purchase); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Purchase)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PurchaseRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PurchaseRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PurchaseRepository_Expecter) FindByID(ctx interface{}, id interface{}) *PurchaseRepository_FindByID_Call {
	return &PurchaseRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *PurchaseRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *PurchaseRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PurchaseRepository_FindByID_Call) Return(_a0 domain.Purchase, _a1 error) *PurchaseRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PurchaseRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (domain.Purchase, error)) *PurchaseRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewPurchaseRepository creates a new instance of PurchaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPurchaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PurchaseRepository {
	mock := &PurchaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
