// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/cashback-service-api/internal/app/cashback/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cashback
func (_m *Repository) Create(ctx context.Context, cashback domain.Cashback) (domain.Cashback, error) {
	ret := _m.Called(ctx, cashback)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Cashback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Cashback) (domain.Cashback, error)); ok {
		return rf(ctx, cashback)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Cashback) domain.Cashback); ok {
		r0 = rf(ctx, cashback)
	} else {
		r0 = ret.Get(0).(domain.Cashback)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Cashback) error); ok {
		r1 = rf(ctx, cashback)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cashback domain.Cashback
func (_e *Repository_Expecter) Create(ctx interface{}, cashback interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, cashback)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, cashback domain.Cashback)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Cashback))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 domain.Cashback, _a1 error) *Repository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, domain.Cashback) (domain.Cashback, error)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPurchaseID provides a mock function with given fields: ctx, purchaseID
func (_m *Repository) FindByPurchaseID(ctx context.Context, purchaseID int64) (domain.Cashback, error) {
	ret := _m.Called(ctx, purchaseID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPurchaseID")
	}

	var r0 domain.Cashback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Cashback, error)); ok {
		return rf(ctx, purchaseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Cashback); ok {
		r0 = rf(ctx, purchaseID)
	} else {
		r0 = ret.Get(0).(domain.Cashback)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, purchaseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByPurchaseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPurchaseID'
type Repository_FindByPurchaseID_Call struct {
	*mock.Call
}

// FindByPurchaseID is a helper method to define mock.On call
//   - ctx context.Context
//   - purchaseID int64
func (_e *Repository_Expecter) FindByPurchaseID(ctx interface{}, purchaseID interface{}) *Repository_FindByPurchaseID_Call {
	return &Repository_FindByPurchaseID_Call{Call: _e.mock.On("FindByPurchaseID", ctx, purchaseID)}
}

func (_c *Repository_FindByPurchaseID_Call) Run(run func(ctx context.Context, purchaseID int64)) *Repository_FindByPurchaseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_FindByPurchaseID_Call) Return(_a0 domain.Cashback, _a1 error) *Repository_FindByPurchaseID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByPurchaseID_Call) RunAndReturn(run func(context.Context, int64) (domain.Cashback, error)) *Repository_FindByPurchaseID_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
