// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/mint-consumer/internal/app/mint/domain"

	mock "github.com/stretchr/testify/mock"
)

// BlockchainClient is an autogenerated mock type for the BlockchainClient type
type BlockchainClient struct {
	mock.Mock
}

type BlockchainClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockchainClient) EXPECT() *BlockchainClient_Expecter {
	return &BlockchainClient_Expecter{mock: &_m.Mock}
}

// MintToken provides a mock function with given fields: ctx, req
func (_m *BlockchainClient) MintToken(ctx context.Context, req domain.MintTokenRequest) (domain.MintResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for MintToken")
	}

	var r0 domain.MintResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MintTokenRequest) (domain.MintResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MintTokenRequest) domain.MintResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.MintResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MintTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockchainClient_MintToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MintToken'
type BlockchainClient_MintToken_Call struct {
	*mock.Call
}

// MintToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.MintTokenRequest
func (_e *BlockchainClient_Expecter) MintToken(ctx interface{}, req interface{}) *BlockchainClient_MintToken_Call {
	return &BlockchainClient_MintToken_Call{Call: _e.mock.On("MintToken", ctx, req)}
}

func (_c *BlockchainClient_MintToken_Call) Run(run func(ctx context.Context, req domain.MintTokenRequest)) *BlockchainClient_MintToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MintTokenRequest))
	})
	return _c
}

func (_c *BlockchainClient_MintToken_Call) Return(_a0 domain.MintResult, _a1 error) *BlockchainClient_MintToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockchainClient_MintToken_Call) RunAndReturn(run func(context.Context, domain.MintTokenRequest) (domain.MintResult, error)) *BlockchainClient_MintToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockchainClient creates a new instance of BlockchainClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockchainClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockchainClient {
	mock := &BlockchainClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
