// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/mint-consumer/internal/app/mint/domain"

	time "time"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateMintRequest provides a mock function with given fields: ctx, req
func (_m *Repository) CreateMintRequest(ctx context.Context, req domain.MintRequest) (domain.MintRequest, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMintRequest")
	}

	var r0 domain.MintRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MintRequest) (domain.MintRequest, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MintRequest) domain.MintRequest); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.MintRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MintRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateMintRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMintRequest'
type Repository_CreateMintRequest_Call struct {
	*mock.Call
}

// CreateMintRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.MintRequest
func (_e *Repository_Expecter) CreateMintRequest(ctx interface{}, req interface{}) *Repository_CreateMintRequest_Call {
	return &Repository_CreateMintRequest_Call{Call: _e.mock.On("CreateMintRequest", ctx, req)}
}

func (_c *Repository_CreateMintRequest_Call) Run(run func(ctx context.Context, req domain.MintRequest)) *Repository_CreateMintRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MintRequest))
	})
	return _c
}

func (_c *Repository_CreateMintRequest_Call) Return(_a0 domain.MintRequest, _a1 error) *Repository_CreateMintRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateMintRequest_Call) RunAndReturn(run func(context.Context, domain.MintRequest) (domain.MintRequest, error)) *Repository_CreateMintRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProcessedEvent provides a mock function with given fields: ctx, eventID, eventType
func (_m *Repository) CreateProcessedEvent(ctx context.Context, eventID uuid.UUID, eventType string) error {
	ret := _m.Called(ctx, eventID, eventType)

	if len(ret) == 0 {
		panic("no return value specified for CreateProcessedEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, eventID, eventType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateProcessedEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProcessedEvent'
type Repository_CreateProcessedEvent_Call struct {
	*mock.Call
}

// CreateProcessedEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - eventType string
func (_e *Repository_Expecter) CreateProcessedEvent(ctx interface{}, eventID interface{}, eventType interface{}) *Repository_CreateProcessedEvent_Call {
	return &Repository_CreateProcessedEvent_Call{Call: _e.mock.On("CreateProcessedEvent", ctx, eventID, eventType)}
}

func (_c *Repository_CreateProcessedEvent_Call) Run(run func(ctx context.Context, eventID uuid.UUID, eventType string)) *Repository_CreateProcessedEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Repository_CreateProcessedEvent_Call) Return(_a0 error) *Repository_CreateProcessedEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateProcessedEvent_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *Repository_CreateProcessedEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsProcessedEvent provides a mock function with given fields: ctx, eventID
func (_m *Repository) ExistsProcessedEvent(ctx context.Context, eventID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsProcessedEvent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ExistsProcessedEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsProcessedEvent'
type Repository_ExistsProcessedEvent_Call struct {
	*mock.Call
}

// ExistsProcessedEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
func (_e *Repository_Expecter) ExistsProcessedEvent(ctx interface{}, eventID interface{}) *Repository_ExistsProcessedEvent_Call {
	return &Repository_ExistsProcessedEvent_Call{Call: _e.mock.On("ExistsProcessedEvent", ctx, eventID)}
}

func (_c *Repository_ExistsProcessedEvent_Call) Run(run func(ctx context.Context, eventID uuid.UUID)) *Repository_ExistsProcessedEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_ExistsProcessedEvent_Call) Return(_a0 bool, _a1 error) *Repository_ExistsProcessedEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ExistsProcessedEvent_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *Repository_ExistsProcessedEvent_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCompleted provides a mock function with given fields: ctx, id, txHash, blockNumber
func (_m *Repository) MarkCompleted(ctx context.Context, id int64, txHash string, blockNumber int64) error {
	ret := _m.Called(ctx, id, txHash, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for MarkCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) error); ok {
		r0 = rf(ctx, id, txHash, blockNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_MarkCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCompleted'
type Repository_MarkCompleted_Call struct {
	*mock.Call
}

// MarkCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - txHash string
//   - blockNumber int64
func (_e *Repository_Expecter) MarkCompleted(ctx interface{}, id interface{}, txHash interface{}, blockNumber interface{}) *Repository_MarkCompleted_Call {
	return &Repository_MarkCompleted_Call{Call: _e.mock.On("MarkCompleted", ctx, id, txHash, blockNumber)}
}

func (_c *Repository_MarkCompleted_Call) Run(run func(ctx context.Context, id int64, txHash string, blockNumber int64)) *Repository_MarkCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *Repository_MarkCompleted_Call) Return(_a0 error) *Repository_MarkCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_MarkCompleted_Call) RunAndReturn(run func(context.Context, int64, string, int64) error) *Repository_MarkCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function with given fields: ctx, id, errorCode, errorMessage, nextRetryAt
func (_m *Repository) MarkFailed(ctx context.Context, id int64, errorCode string, errorMessage string, nextRetryAt *time.Time) error {
	ret := _m.Called(ctx, id, errorCode, errorMessage, nextRetryAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, *time.Time) error); ok {
		r0 = rf(ctx, id, errorCode, errorMessage, nextRetryAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type Repository_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - errorCode string
//   - errorMessage string
//   - nextRetryAt *time.Time
func (_e *Repository_Expecter) MarkFailed(ctx interface{}, id interface{}, errorCode interface{}, errorMessage interface{}, nextRetryAt interface{}) *Repository_MarkFailed_Call {
	return &Repository_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id, errorCode, errorMessage, nextRetryAt)}
}

func (_c *Repository_MarkFailed_Call) Run(run func(ctx context.Context, id int64, errorCode string, errorMessage string, nextRetryAt *time.Time)) *Repository_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string), args[4].(*time.Time))
	})
	return _c
}

func (_c *Repository_MarkFailed_Call) Return(_a0 error) *Repository_MarkFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_MarkFailed_Call) RunAndReturn(run func(context.Context, int64, string, string, *time.Time) error) *Repository_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
