// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BlockReader is an autogenerated mock type for the BlockReader type
type BlockReader struct {
	mock.Mock
}

type BlockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockReader) EXPECT() *BlockReader_Expecter {
	return &BlockReader_Expecter{mock: &_m.Mock}
}

// BlockNumber provides a mock function with given fields: ctx
func (_m *BlockReader) BlockNumber(ctx context.Context) (uint64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BlockNumber")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockReader_BlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockNumber'
type BlockReader_BlockNumber_Call struct {
	*mock.Call
}

// BlockNumber is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BlockReader_Expecter) BlockNumber(ctx interface{}) *BlockReader_BlockNumber_Call {
	return &BlockReader_BlockNumber_Call{Call: _e.mock.On("BlockNumber", ctx)}
}

func (_c *BlockReader_BlockNumber_Call) Run(run func(ctx context.Context)) *BlockReader_BlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BlockReader_BlockNumber_Call) Return(_a0 uint64, _a1 error) *BlockReader_BlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockReader_BlockNumber_Call) RunAndReturn(run func(context.Context) (uint64, error)) *BlockReader_BlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockReader creates a new instance of BlockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockReader {
	mock := &BlockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
