// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	chain "github.com/cashback-platform/services/blockchain-adapter/internal/chain"

	mock "github.com/stretchr/testify/mock"
)

// TokenFilter is an autogenerated mock type for the TokenFilter type
type TokenFilter struct {
	mock.Mock
}

type TokenFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenFilter) EXPECT() *TokenFilter_Expecter {
	return &TokenFilter_Expecter{mock: &_m.Mock}
}

// FilterTransfers provides a mock function with given fields: ctx, fromBlock, toBlock
func (_m *TokenFilter) FilterTransfers(ctx context.Context, fromBlock uint64, toBlock uint64) ([]chain.Deposit, error) {
	ret := _m.Called(ctx, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for FilterTransfers")
	}

	var r0 []chain.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]chain.Deposit, error)); ok {
		return rf(ctx, fromBlock, toBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []chain.Deposit); ok {
		r0 = rf(ctx, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chain.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, fromBlock, toBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenFilter_FilterTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterTransfers'
type TokenFilter_FilterTransfers_Call struct {
	*mock.Call
}

// FilterTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock uint64
//   - toBlock uint64
func (_e *TokenFilter_Expecter) FilterTransfers(ctx interface{}, fromBlock interface{}, toBlock interface{}) *TokenFilter_FilterTransfers_Call {
	return &TokenFilter_FilterTransfers_Call{Call: _e.mock.On("FilterTransfers", ctx, fromBlock, toBlock)}
}

func (_c *TokenFilter_FilterTransfers_Call) Run(run func(ctx context.Context, fromBlock uint64, toBlock uint64)) *TokenFilter_FilterTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *TokenFilter_FilterTransfers_Call) Return(_a0 []chain.Deposit, _a1 error) *TokenFilter_FilterTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenFilter_FilterTransfers_Call) RunAndReturn(run func(context.Context, uint64, uint64) ([]chain.Deposit, error)) *TokenFilter_FilterTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenFilter creates a new instance of TokenFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenFilter {
	mock := &TokenFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
