// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/token.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MintStatus represents the status of a mint operation
type MintStatus int32

const (
	MintStatus_MINT_STATUS_UNSPECIFIED MintStatus = 0
	MintStatus_MINT_STATUS_PENDING     MintStatus = 1
	MintStatus_MINT_STATUS_SUBMITTED   MintStatus = 2
	MintStatus_MINT_STATUS_CONFIRMED   MintStatus = 3
	MintStatus_MINT_STATUS_FAILED      MintStatus = 4
)

// Enum value maps for MintStatus.
var (
	MintStatus_name = map[int32]string{
		0: "MINT_STATUS_UNSPECIFIED",
		1: "MINT_STATUS_PENDING",
		2: "MINT_STATUS_SUBMITTED",
		3: "MINT_STATUS_CONFIRMED",
		4: "MINT_STATUS_FAILED",
	}
	MintStatus_value = map[string]int32{
		"MINT_STATUS_UNSPECIFIED": 0,
		"MINT_STATUS_PENDING":     1,
		"MINT_STATUS_SUBMITTED":   2,
		"MINT_STATUS_CONFIRMED":   3,
		"MINT_STATUS_FAILED":      4,
	}
)

func (x MintStatus) Enum() *MintStatus {
	p := new(MintStatus)
	*p = x
	return p
}

func (x MintStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MintStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_token_proto_enumTypes[0].Descriptor()
}

func (MintStatus) Type() protoreflect.EnumType {
	return &file_proto_token_proto_enumTypes[0]
}

func (x MintStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MintStatus.Descriptor instead.
func (MintStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{0}
}

// TransactionStatus represents the status of a blockchain transaction
type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING     TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_CONFIRMED   TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FAILED      TransactionStatus = 3
	TransactionStatus_TRANSACTION_STATUS_NOT_FOUND   TransactionStatus = 4
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_CONFIRMED",
		3: "TRANSACTION_STATUS_FAILED",
		4: "TRANSACTION_STATUS_NOT_FOUND",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_CONFIRMED":   2,
		"TRANSACTION_STATUS_FAILED":      3,
		"TRANSACTION_STATUS_NOT_FOUND":   4,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_token_proto_enumTypes[1].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_proto_token_proto_enumTypes[1]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{1}
}

// MintTokenRequest represents a request to mint tokens
type MintTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for idempotency
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Wallet address to receive the tokens (0x prefixed hex)
	WalletAddress string `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	// Amount of tokens to mint (wei representation as string)
	TokenAmount string `protobuf:"bytes,3,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	// Optional metadata for the mint operation
	Metadata *MintMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Chain identifier: "ethereum" or "solana"
	ChainId       string `protobuf:"bytes,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenRequest) Reset() {
	*x = MintTokenRequest{}
	mi := &file_proto_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenRequest) ProtoMessage() {}

func (x *MintTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenRequest.ProtoReflect.Descriptor instead.
func (*MintTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{0}
}

func (x *MintTokenRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *MintTokenRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *MintTokenRequest) GetTokenAmount() string {
	if x != nil {
		return x.TokenAmount
	}
	return ""
}

func (x *MintTokenRequest) GetMetadata() *MintMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MintTokenRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// MintMetadata contains optional metadata for mint operations
type MintMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the cashback ID
	CashbackId string `protobuf:"bytes,1,opt,name=cashback_id,json=cashbackId,proto3" json:"cashback_id,omitempty"`
	// Reference to the user ID
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Additional key-value metadata
	Extra         map[string]string `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintMetadata) Reset() {
	*x = MintMetadata{}
	mi := &file_proto_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintMetadata) ProtoMessage() {}

func (x *MintMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintMetadata.ProtoReflect.Descriptor instead.
func (*MintMetadata) Descriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{1}
}

func (x *MintMetadata) GetCashbackId() string {
	if x != nil {
		return x.CashbackId
	}
	return ""
}

func (x *MintMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MintMetadata) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// MintTokenResponse represents the result of a mint operation
type MintTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the mint was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Transaction hash (if submitted to blockchain)
	TransactionHash string `protobuf:"bytes,2,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	// Block number where transaction was included (if confirmed)
	BlockNumber int64 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// Status of the mint operation
	Status MintStatus `protobuf:"varint,4,opt,name=status,proto3,enum=token.MintStatus" json:"status,omitempty"`
	// Error details (if failed)
	Error         *MintError `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenResponse) Reset() {
	*x = MintTokenResponse{}
	mi := &file_proto_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenResponse) ProtoMessage() {}

func (x *MintTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenResponse.ProtoReflect.Descriptor instead.
func (*MintTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{2}
}

func (x *MintTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MintTokenResponse) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *MintTokenResponse) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *MintTokenResponse) GetStatus() MintStatus {
	if x != nil {
		return x.Status
	}
	return MintStatus_MINT_STATUS_UNSPECIFIED
}

func (x *MintTokenResponse) GetError() *MintError {
	if x != nil {
		return x.Error
	}
	return nil
}

// MintError contains error details for failed mint operations
type MintError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code for programmatic handling
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Whether the error is retryable
	Retryable     bool `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintError) Reset() {
	*x = MintError{}
	mi := &file_proto_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintError) ProtoMessage() {}

func (x *MintError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintError.ProtoReflect.Descriptor instead.
func (*MintError) Descriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{3}
}

func (x *MintError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MintError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MintError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// GetBalanceRequest represents a request to get token balance
type GetBalanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wallet address to check balance (0x prefixed hex)
	WalletAddress string `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

// GetBalanceResponse represents the token balance
type GetBalanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wallet address
	WalletAddress string `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	// Token balance (wei representation as string)
	Balance string `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	// Block number at which balance was read
	BlockNumber   int64 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetBalanceResponse) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

// GetTransactionRequest represents a request to get transaction status
type GetTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction hash to look up
	TransactionHash string `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionRequest) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

// GetTransactionResponse represents transaction details
type GetTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction hash
	TransactionHash string `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	// Transaction status
	Status TransactionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=token.TransactionStatus" json:"status,omitempty"`
	// Block number (if included in a block)
	BlockNumber int64 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// Number of confirmations
	Confirmations int64 `protobuf:"varint,4,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	// Gas used
	GasUsed int64 `protobuf:"varint,5,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// Whether the transaction succeeded
	Success       bool `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_proto_token_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionResponse) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *GetTransactionResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *GetTransactionResponse) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetTransactionResponse) GetConfirmations() int64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *GetTransactionResponse) GetGasUsed() int64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *GetTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_token_proto protoreflect.FileDescriptor

const file_proto_token_proto_rawDesc = "" +
	"\n" +
	"\x11proto/token.proto\x12\x05token\"\xd1\x01\n" +
	"\x10MintTokenRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12!\n" +
	"\ftoken_amount\x18\x03 \x01(\tR\vtokenAmount\x12/\n" +
	"\bmetadata\x18\x04 \x01(\v2\x13.token.MintMetadataR\bmetadata\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\tR\achainId\"\xb8\x01\n" +
	"\fMintMetadata\x12\x1f\n" +
	"\vcashback_id\x18\x01 \x01(\tR\n" +
	"cashbackId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x124\n" +
	"\x05extra\x18\x03 \x03(\v2\x1e.token.MintMetadata.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\x11MintTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10transaction_hash\x18\x02 \x01(\tR\x0ftransactionHash\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x03R\vblockNumber\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.token.MintStatusR\x06status\x12&\n" +
	"\x05error\x18\x05 \x01(\v2\x10.token.MintErrorR\x05error\"W\n" +
	"\tMintError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\":\n" +
	"\x11GetBalanceRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\"x\n" +
	"\x12GetBalanceResponse\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x03R\vblockNumber\"B\n" +
	"\x15GetTransactionRequest\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHash\"\xf3\x01\n" +
	"\x16GetTransactionResponse\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHash\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.token.TransactionStatusR\x06status\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x03R\vblockNumber\x12$\n" +
	"\rconfirmations\x18\x04 \x01(\x03R\rconfirmations\x12\x19\n" +
	"\bgas_used\x18\x05 \x01(\x03R\agasUsed\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess*\x90\x01\n" +
	"\n" +
	"MintStatus\x12\x1b\n" +
	"\x17MINT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MINT_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15MINT_STATUS_SUBMITTED\x10\x02\x12\x19\n" +
	"\x15MINT_STATUS_CONFIRMED\x10\x03\x12\x16\n" +
	"\x12MINT_STATUS_FAILED\x10\x04*\xba\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cTRANSACTION_STATUS_CONFIRMED\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x03\x12 \n" +
	"\x1cTRANSACTION_STATUS_NOT_FOUND\x10\x042\xe0\x01\n" +
	"\fTokenService\x12>\n" +
	"\tMintToken\x12\x17.token.MintTokenRequest\x1a\x18.token.MintTokenResponse\x12A\n" +
	"\n" +
	"GetBalance\x12\x18.token.GetBalanceRequest\x1a\x19.token.GetBalanceResponse\x12M\n" +
	"\x0eGetTransaction\x12\x1c.token.GetTransactionRequest\x1a\x1d.token.GetTransactionResponseB*Z(github.com/cashback-platform/proto/tokenb\x06proto3"

var (
	file_proto_token_proto_rawDescOnce sync.Once
	file_proto_token_proto_rawDescData []byte
)

func file_proto_token_proto_rawDescGZIP() []byte {
	file_proto_token_proto_rawDescOnce.Do(func() {
		file_proto_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_proto_rawDesc), len(file_proto_token_proto_rawDesc)))
	})
	return file_proto_token_proto_rawDescData
}

var file_proto_token_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_token_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_token_proto_goTypes = []any{
	(MintStatus)(0),                // 0: token.MintStatus
	(TransactionStatus)(0),         // 1: token.TransactionStatus
	(*MintTokenRequest)(nil),       // 2: token.MintTokenRequest
	(*MintMetadata)(nil),           // 3: token.MintMetadata
	(*MintTokenResponse)(nil),      // 4: token.MintTokenResponse
	(*MintError)(nil),              // 5: token.MintError
	(*GetBalanceRequest)(nil),      // 6: token.GetBalanceRequest
	(*GetBalanceResponse)(nil),     // 7: token.GetBalanceResponse
	(*GetTransactionRequest)(nil),  // 8: token.GetTransactionRequest
	(*GetTransactionResponse)(nil), // 9: token.GetTransactionResponse
	nil,                            // 10: token.MintMetadata.ExtraEntry
}
var file_proto_token_proto_depIdxs = []int32{
	3,  // 0: token.MintTokenRequest.metadata:type_name -> token.MintMetadata
	10, // 1: token.MintMetadata.extra:type_name -> token.MintMetadata.ExtraEntry
	0,  // 2: token.MintTokenResponse.status:type_name -> token.MintStatus
	5,  // 3: token.MintTokenResponse.error:type_name -> token.MintError
	1,  // 4: token.GetTransactionResponse.status:type_name -> token.TransactionStatus
	2,  // 5: token.TokenService.MintToken:input_type -> token.MintTokenRequest
	6,  // 6: token.TokenService.GetBalance:input_type -> token.GetBalanceRequest
	8,  // 7: token.TokenService.GetTransaction:input_type -> token.GetTransactionRequest
	4,  // 8: token.TokenService.MintToken:output_type -> token.MintTokenResponse
	7,  // 9: token.TokenService.GetBalance:output_type -> token.GetBalanceResponse
	9,  // 10: token.TokenService.GetTransaction:output_type -> token.GetTransactionResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_token_proto_init() }
func file_proto_token_proto_init() {
	if File_proto_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_proto_rawDesc), len(file_proto_token_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_token_proto_goTypes,
		DependencyIndexes: file_proto_token_proto_depIdxs,
		EnumInfos:         file_proto_token_proto_enumTypes,
		MessageInfos:      file_proto_token_proto_msgTypes,
	}.Build()
	File_proto_token_proto = out.File
	file_proto_token_proto_goTypes = nil
	file_proto_token_proto_depIdxs = nil
}
