// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/cashback-service-api/internal/app/cashback/domain"
	mock "github.com/stretchr/testify/mock"
)

// CashbackRepository is an autogenerated mock type for the CashbackRepository type
type CashbackRepository struct {
	mock.Mock
}

type CashbackRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CashbackRepository) EXPECT() *CashbackRepository_Expecter {
	return &CashbackRepository_Expecter{mock: &_m.Mock}
}

// CreateWithEvent provides a mock function with given fields: ctx, cashback, eventFn
func (_m *CashbackRepository) CreateWithEvent(ctx context.Context, cashback domain.Cashback, eventFn func(domain.Cashback) interface{}) (domain.Cashback, error) {
	ret := _m.Called(ctx, cashback, eventFn)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithEvent")
	}

	var r0 domain.Cashback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Cashback, func(domain.Cashback) interface{}) (domain.Cashback, error)); ok {
		return rf(ctx, cashback, eventFn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Cashback, func(domain.Cashback) interface{}) domain.Cashback); ok {
		r0 = rf(ctx, cashback, eventFn)
	} else {
		r0 = ret.Get(0).(domain.Cashback)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Cashback, func(domain.Cashback) interface{}) error); ok {
		r1 = rf(ctx, cashback, eventFn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashbackRepository_CreateWithEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithEvent'
type CashbackRepository_CreateWithEvent_Call struct {
	*mock.Call
}

// CreateWithEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - cashback domain.Cashback
//   - eventFn func(domain.Cashback) interface{}
func (_e *CashbackRepository_Expecter) CreateWithEvent(ctx interface{}, cashback interface{}, eventFn interface{}) *CashbackRepository_CreateWithEvent_Call {
	return &CashbackRepository_CreateWithEvent_Call{Call: _e.mock.On("CreateWithEvent", ctx, cashback, eventFn)}
}

func (_c *CashbackRepository_CreateWithEvent_Call) Run(run func(ctx context.Context, cashback domain.Cashback, eventFn func(domain.Cashback) interface{})) *CashbackRepository_CreateWithEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Cashback), args[2].(func(domain.Cashback) interface{}))
	})
	return _c
}

func (_c *CashbackRepository_CreateWithEvent_Call) Return(_a0 domain.Cashback, _a1 error) *CashbackRepository_CreateWithEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CashbackRepository_CreateWithEvent_Call) RunAndReturn(run func(context.Context, domain.Cashback, func(domain.Cashback) interface{}) (domain.Cashback, error)) *CashbackRepository_CreateWithEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewCashbackRepository creates a new instance of CashbackRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCashbackRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CashbackRepository {
	mock := &CashbackRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
