// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/cashback-service-api/internal/app/deposit/domain"
	mock "github.com/stretchr/testify/mock"
)

// DepositRepository is an autogenerated mock type for the DepositRepository type
type DepositRepository struct {
	mock.Mock
}

type DepositRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DepositRepository) EXPECT() *DepositRepository_Expecter {
	return &DepositRepository_Expecter{mock: &_m.Mock}
}

// ExistsByTxHash provides a mock function with given fields: ctx, txHash
func (_m *DepositRepository) ExistsByTxHash(ctx context.Context, txHash string) (bool, error) {
	ret := _m.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByTxHash")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, txHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, txHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepositRepository_ExistsByTxHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByTxHash'
type DepositRepository_ExistsByTxHash_Call struct {
	*mock.Call
}

// ExistsByTxHash is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash string
func (_e *DepositRepository_Expecter) ExistsByTxHash(ctx interface{}, txHash interface{}) *DepositRepository_ExistsByTxHash_Call {
	return &DepositRepository_ExistsByTxHash_Call{Call: _e.mock.On("ExistsByTxHash", ctx, txHash)}
}

func (_c *DepositRepository_ExistsByTxHash_Call) Run(run func(ctx context.Context, txHash string)) *DepositRepository_ExistsByTxHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DepositRepository_ExistsByTxHash_Call) Return(_a0 bool, _a1 error) *DepositRepository_ExistsByTxHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DepositRepository_ExistsByTxHash_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *DepositRepository_ExistsByTxHash_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, receipt
func (_m *DepositRepository) Save(ctx context.Context, receipt domain.DepositReceipt) (domain.DepositReceipt, error) {
	ret := _m.Called(ctx, receipt)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 domain.DepositReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.DepositReceipt) (domain.DepositReceipt, error)); ok {
		return rf(ctx, receipt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.DepositReceipt) domain.DepositReceipt); ok {
		r0 = rf(ctx, receipt)
	} else {
		r0 = ret.Get(0).(domain.DepositReceipt)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.DepositReceipt) error); ok {
		r1 = rf(ctx, receipt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepositRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type DepositRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - receipt domain.DepositReceipt
func (_e *DepositRepository_Expecter) Save(ctx interface{}, receipt interface{}) *DepositRepository_Save_Call {
	return &DepositRepository_Save_Call{Call: _e.mock.On("Save", ctx, receipt)}
}

func (_c *DepositRepository_Save_Call) Run(run func(ctx context.Context, receipt domain.DepositReceipt)) *DepositRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.DepositReceipt))
	})
	return _c
}

func (_c *DepositRepository_Save_Call) Return(_a0 domain.DepositReceipt, _a1 error) *DepositRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DepositRepository_Save_Call) RunAndReturn(run func(context.Context, domain.DepositReceipt) (domain.DepositReceipt, error)) *DepositRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewDepositRepository creates a new instance of DepositRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepositRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepositRepository {
	mock := &DepositRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
