// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/cashback-service-api/internal/app/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// FindByWalletAddress provides a mock function with given fields: ctx, walletAddress
func (_m *UserRepository) FindByWalletAddress(ctx context.Context, walletAddress string) (domain.User, error) {
	ret := _m.Called(ctx, walletAddress)

	if len(ret) == 0 {
		panic("no return value specified for FindByWalletAddress")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, walletAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, walletAddress)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, walletAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_FindByWalletAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWalletAddress'
type UserRepository_FindByWalletAddress_Call struct {
	*mock.Call
}

// FindByWalletAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - walletAddress string
func (_e *UserRepository_Expecter) FindByWalletAddress(ctx interface{}, walletAddress interface{}) *UserRepository_FindByWalletAddress_Call {
	return &UserRepository_FindByWalletAddress_Call{Call: _e.mock.On("FindByWalletAddress", ctx, walletAddress)}
}

func (_c *UserRepository_FindByWalletAddress_Call) Run(run func(ctx context.Context, walletAddress string)) *UserRepository_FindByWalletAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_FindByWalletAddress_Call) Return(_a0 domain.User, _a1 error) *UserRepository_FindByWalletAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_FindByWalletAddress_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *UserRepository_FindByWalletAddress_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
