[tools]
go = "1.26"

[tasks.build]
run = "go build -o ../../bin/mint-consumer ./cmd/main.go"

[tasks.run]
run = "go run ./cmd/main.go"

[tasks.test]
run = "go test -v -race ./..."

[tasks.lint]
run = "golangci-lint run"

[tasks.deps]
run = "go mod tidy"
