// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NonceRepository is an autogenerated mock type for the NonceRepository type
type NonceRepository struct {
	mock.Mock
}

type NonceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NonceRepository) EXPECT() *NonceRepository_Expecter {
	return &NonceRepository_Expecter{mock: &_m.Mock}
}

// CurrentNonce provides a mock function with given fields: ctx, walletAddress
func (_m *NonceRepository) CurrentNonce(ctx context.Context, walletAddress string) (int64, error) {
	ret := _m.Called(ctx, walletAddress)

	if len(ret) == 0 {
		panic("no return value specified for CurrentNonce")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, walletAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, walletAddress)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, walletAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NonceRepository_CurrentNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentNonce'
type NonceRepository_CurrentNonce_Call struct {
	*mock.Call
}

// CurrentNonce is a helper method to define mock.On call
//   - ctx context.Context
//   - walletAddress string
func (_e *NonceRepository_Expecter) CurrentNonce(ctx interface{}, walletAddress interface{}) *NonceRepository_CurrentNonce_Call {
	return &NonceRepository_CurrentNonce_Call{Call: _e.mock.On("CurrentNonce", ctx, walletAddress)}
}

func (_c *NonceRepository_CurrentNonce_Call) Run(run func(ctx context.Context, walletAddress string)) *NonceRepository_CurrentNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NonceRepository_CurrentNonce_Call) Return(_a0 int64, _a1 error) *NonceRepository_CurrentNonce_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NonceRepository_CurrentNonce_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *NonceRepository_CurrentNonce_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: ctx, walletAddress
func (_m *NonceRepository) Increment(ctx context.Context, walletAddress string) (int64, error) {
	ret := _m.Called(ctx, walletAddress)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, walletAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, walletAddress)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, walletAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NonceRepository_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type NonceRepository_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - walletAddress string
func (_e *NonceRepository_Expecter) Increment(ctx interface{}, walletAddress interface{}) *NonceRepository_Increment_Call {
	return &NonceRepository_Increment_Call{Call: _e.mock.On("Increment", ctx, walletAddress)}
}

func (_c *NonceRepository_Increment_Call) Run(run func(ctx context.Context, walletAddress string)) *NonceRepository_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NonceRepository_Increment_Call) Return(_a0 int64, _a1 error) *NonceRepository_Increment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NonceRepository_Increment_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *NonceRepository_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// SyncFromChain provides a mock function with given fields: ctx, walletAddress, nonce
func (_m *NonceRepository) SyncFromChain(ctx context.Context, walletAddress string, nonce int64) error {
	ret := _m.Called(ctx, walletAddress, nonce)

	if len(ret) == 0 {
		panic("no return value specified for SyncFromChain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, walletAddress, nonce)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NonceRepository_SyncFromChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncFromChain'
type NonceRepository_SyncFromChain_Call struct {
	*mock.Call
}

// SyncFromChain is a helper method to define mock.On call
//   - ctx context.Context
//   - walletAddress string
//   - nonce int64
func (_e *NonceRepository_Expecter) SyncFromChain(ctx interface{}, walletAddress interface{}, nonce interface{}) *NonceRepository_SyncFromChain_Call {
	return &NonceRepository_SyncFromChain_Call{Call: _e.mock.On("SyncFromChain", ctx, walletAddress, nonce)}
}

func (_c *NonceRepository_SyncFromChain_Call) Run(run func(ctx context.Context, walletAddress string, nonce int64)) *NonceRepository_SyncFromChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *NonceRepository_SyncFromChain_Call) Return(_a0 error) *NonceRepository_SyncFromChain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NonceRepository_SyncFromChain_Call) RunAndReturn(run func(context.Context, string, int64) error) *NonceRepository_SyncFromChain_Call {
	_c.Call.Return(run)
	return _c
}

// NewNonceRepository creates a new instance of NonceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNonceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NonceRepository {
	mock := &NonceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
