// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	big "math/big"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind/v2"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	mock "github.com/stretchr/testify/mock"
)

// TokenContract is an autogenerated mock type for the TokenContract type
type TokenContract struct {
	mock.Mock
}

type TokenContract_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenContract) EXPECT() *TokenContract_Expecter {
	return &TokenContract_Expecter{mock: &_m.Mock}
}

// BalanceOf provides a mock function with given fields: opts, account
func (_m *TokenContract) BalanceOf(opts *bind.CallOpts, account common.Address) (*big.Int, error) {
	ret := _m.Called(opts, account)

	if len(ret) == 0 {
		panic("no return value specified for BalanceOf")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (*big.Int, error)); ok {
		return rf(opts, account)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) *big.Int); ok {
		r0 = rf(opts, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenContract_BalanceOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceOf'
type TokenContract_BalanceOf_Call struct {
	*mock.Call
}

// BalanceOf is a helper method to define mock.On call
//   - opts *bind.CallOpts
//   - account common.Address
func (_e *TokenContract_Expecter) BalanceOf(opts interface{}, account interface{}) *TokenContract_BalanceOf_Call {
	return &TokenContract_BalanceOf_Call{Call: _e.mock.On("BalanceOf", opts, account)}
}

func (_c *TokenContract_BalanceOf_Call) Run(run func(opts *bind.CallOpts, account common.Address)) *TokenContract_BalanceOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts), args[1].(common.Address))
	})
	return _c
}

func (_c *TokenContract_BalanceOf_Call) Return(_a0 *big.Int, _a1 error) *TokenContract_BalanceOf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenContract_BalanceOf_Call) RunAndReturn(run func(*bind.CallOpts, common.Address) (*big.Int, error)) *TokenContract_BalanceOf_Call {
	_c.Call.Return(run)
	return _c
}

// Mint provides a mock function with given fields: opts, to, amount
func (_m *TokenContract) Mint(opts *bind.TransactOpts, to common.Address, amount *big.Int) (*types.Transaction, error) {
	ret := _m.Called(opts, to, amount)

	if len(ret) == 0 {
		panic("no return value specified for Mint")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, *big.Int) (*types.Transaction, error)); ok {
		return rf(opts, to, amount)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, *big.Int) *types.Transaction); ok {
		r0 = rf(opts, to, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address, *big.Int) error); ok {
		r1 = rf(opts, to, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenContract_Mint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mint'
type TokenContract_Mint_Call struct {
	*mock.Call
}

// Mint is a helper method to define mock.On call
//   - opts *bind.TransactOpts
//   - to common.Address
//   - amount *big.Int
func (_e *TokenContract_Expecter) Mint(opts interface{}, to interface{}, amount interface{}) *TokenContract_Mint_Call {
	return &TokenContract_Mint_Call{Call: _e.mock.On("Mint", opts, to, amount)}
}

func (_c *TokenContract_Mint_Call) Run(run func(opts *bind.TransactOpts, to common.Address, amount *big.Int)) *TokenContract_Mint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.TransactOpts), args[1].(common.Address), args[2].(*big.Int))
	})
	return _c
}

func (_c *TokenContract_Mint_Call) Return(_a0 *types.Transaction, _a1 error) *TokenContract_Mint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenContract_Mint_Call) RunAndReturn(run func(*bind.TransactOpts, common.Address, *big.Int) (*types.Transaction, error)) *TokenContract_Mint_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenContract creates a new instance of TokenContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenContract {
	mock := &TokenContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
