// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/mint-consumer/internal/app/mint/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// FindFailedRetryable provides a mock function with given fields: ctx, limit
func (_m *Repository) FindFailedRetryable(ctx context.Context, limit int) ([]domain.MintRequest, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindFailedRetryable")
	}

	var r0 []domain.MintRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.MintRequest, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.MintRequest); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MintRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindFailedRetryable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFailedRetryable'
type Repository_FindFailedRetryable_Call struct {
	*mock.Call
}

// FindFailedRetryable is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *Repository_Expecter) FindFailedRetryable(ctx interface{}, limit interface{}) *Repository_FindFailedRetryable_Call {
	return &Repository_FindFailedRetryable_Call{Call: _e.mock.On("FindFailedRetryable", ctx, limit)}
}

func (_c *Repository_FindFailedRetryable_Call) Run(run func(ctx context.Context, limit int)) *Repository_FindFailedRetryable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Repository_FindFailedRetryable_Call) Return(_a0 []domain.MintRequest, _a1 error) *Repository_FindFailedRetryable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindFailedRetryable_Call) RunAndReturn(run func(context.Context, int) ([]domain.MintRequest, error)) *Repository_FindFailedRetryable_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCompleted provides a mock function with given fields: ctx, id, txHash, blockNumber
func (_m *Repository) MarkCompleted(ctx context.Context, id int64, txHash string, blockNumber int64) error {
	ret := _m.Called(ctx, id, txHash, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for MarkCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) error); ok {
		r0 = rf(ctx, id, txHash, blockNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_MarkCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCompleted'
type Repository_MarkCompleted_Call struct {
	*mock.Call
}

// MarkCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - txHash string
//   - blockNumber int64
func (_e *Repository_Expecter) MarkCompleted(ctx interface{}, id interface{}, txHash interface{}, blockNumber interface{}) *Repository_MarkCompleted_Call {
	return &Repository_MarkCompleted_Call{Call: _e.mock.On("MarkCompleted", ctx, id, txHash, blockNumber)}
}

func (_c *Repository_MarkCompleted_Call) Run(run func(ctx context.Context, id int64, txHash string, blockNumber int64)) *Repository_MarkCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *Repository_MarkCompleted_Call) Return(_a0 error) *Repository_MarkCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_MarkCompleted_Call) RunAndReturn(run func(context.Context, int64, string, int64) error) *Repository_MarkCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function with given fields: ctx, id, errorCode, errorMessage, nextRetryAt
func (_m *Repository) MarkFailed(ctx context.Context, id int64, errorCode string, errorMessage string, nextRetryAt *time.Time) error {
	ret := _m.Called(ctx, id, errorCode, errorMessage, nextRetryAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, *time.Time) error); ok {
		r0 = rf(ctx, id, errorCode, errorMessage, nextRetryAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type Repository_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - errorCode string
//   - errorMessage string
//   - nextRetryAt *time.Time
func (_e *Repository_Expecter) MarkFailed(ctx interface{}, id interface{}, errorCode interface{}, errorMessage interface{}, nextRetryAt interface{}) *Repository_MarkFailed_Call {
	return &Repository_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id, errorCode, errorMessage, nextRetryAt)}
}

func (_c *Repository_MarkFailed_Call) Run(run func(ctx context.Context, id int64, errorCode string, errorMessage string, nextRetryAt *time.Time)) *Repository_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string), args[4].(*time.Time))
	})
	return _c
}

func (_c *Repository_MarkFailed_Call) Return(_a0 error) *Repository_MarkFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_MarkFailed_Call) RunAndReturn(run func(context.Context, int64, string, string, *time.Time) error) *Repository_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
