// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cashback-platform/services/blockchain-adapter/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx
func (_m *TransactionRepository) Create(ctx context.Context, tx domain.BlockchainTransaction) (domain.BlockchainTransaction, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.BlockchainTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BlockchainTransaction) (domain.BlockchainTransaction, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BlockchainTransaction) domain.BlockchainTransaction); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Get(0).(domain.BlockchainTransaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BlockchainTransaction) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx domain.BlockchainTransaction
func (_e *TransactionRepository_Expecter) Create(ctx interface{}, tx interface{}) *TransactionRepository_Create_Call {
	return &TransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx)}
}

func (_c *TransactionRepository_Create_Call) Run(run func(ctx context.Context, tx domain.BlockchainTransaction)) *TransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.BlockchainTransaction))
	})
	return _c
}

func (_c *TransactionRepository_Create_Call) Return(_a0 domain.BlockchainTransaction, _a1 error) *TransactionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_Create_Call) RunAndReturn(run func(context.Context, domain.BlockchainTransaction) (domain.BlockchainTransaction, error)) *TransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdempotencyKey provides a mock function with given fields: ctx, key
func (_m *TransactionRepository) FindByIdempotencyKey(ctx context.Context, key uuid.UUID) (*domain.BlockchainTransaction, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdempotencyKey")
	}

	var r0 *domain.BlockchainTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.BlockchainTransaction, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.BlockchainTransaction); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlockchainTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_FindByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdempotencyKey'
type TransactionRepository_FindByIdempotencyKey_Call struct {
	*mock.Call
}

// FindByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key uuid.UUID
func (_e *TransactionRepository_Expecter) FindByIdempotencyKey(ctx interface{}, key interface{}) *TransactionRepository_FindByIdempotencyKey_Call {
	return &TransactionRepository_FindByIdempotencyKey_Call{Call: _e.mock.On("FindByIdempotencyKey", ctx, key)}
}

func (_c *TransactionRepository_FindByIdempotencyKey_Call) Run(run func(ctx context.Context, key uuid.UUID)) *TransactionRepository_FindByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TransactionRepository_FindByIdempotencyKey_Call) Return(_a0 *domain.BlockchainTransaction, _a1 error) *TransactionRepository_FindByIdempotencyKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_FindByIdempotencyKey_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.BlockchainTransaction, error)) *TransactionRepository_FindByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function with given fields: ctx, id, errCode, errMsg
func (_m *TransactionRepository) MarkFailed(ctx context.Context, id int64, errCode string, errMsg string) error {
	ret := _m.Called(ctx, id, errCode, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = rf(ctx, id, errCode, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type TransactionRepository_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - errCode string
//   - errMsg string
func (_e *TransactionRepository_Expecter) MarkFailed(ctx interface{}, id interface{}, errCode interface{}, errMsg interface{}) *TransactionRepository_MarkFailed_Call {
	return &TransactionRepository_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id, errCode, errMsg)}
}

func (_c *TransactionRepository_MarkFailed_Call) Run(run func(ctx context.Context, id int64, errCode string, errMsg string)) *TransactionRepository_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *TransactionRepository_MarkFailed_Call) Return(_a0 error) *TransactionRepository_MarkFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_MarkFailed_Call) RunAndReturn(run func(context.Context, int64, string, string) error) *TransactionRepository_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, txHash, blockNumber
func (_m *TransactionRepository) UpdateStatus(ctx context.Context, id int64, status domain.TransactionStatus, txHash string, blockNumber int64) error {
	ret := _m.Called(ctx, id, status, txHash, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.TransactionStatus, string, int64) error); ok {
		r0 = rf(ctx, id, status, txHash, blockNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type TransactionRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status domain.TransactionStatus
//   - txHash string
//   - blockNumber int64
func (_e *TransactionRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, txHash interface{}, blockNumber interface{}) *TransactionRepository_UpdateStatus_Call {
	return &TransactionRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, txHash, blockNumber)}
}

func (_c *TransactionRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id int64, status domain.TransactionStatus, txHash string, blockNumber int64)) *TransactionRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.TransactionStatus), args[3].(string), args[4].(int64))
	})
	return _c
}

func (_c *TransactionRepository_UpdateStatus_Call) Return(_a0 error) *TransactionRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, domain.TransactionStatus, string, int64) error) *TransactionRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
